default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres

development:
  <<: *default
  adapter: postgresql
  database: happenings-server_development
  username: postgres

test:
  <<: *default
  database: happenings-server_test

production:
  <<: *default
  pool: <%= ENV["DB_POOL"] || ENV["MAX_THREADS"] || 5 %>
  url:  <%= ENV["DATABASE_URL"] %>
